### ISSUE TITLE
tapiro generated code will need a JsonCodec for _primitive_ types (String, Int, ...)

### ISSUE THREAD

**Issue by giuscri** [buildo/retro#180]
As of 701630c993ef905fc0fa40bada22440c031e6ef0, tapiro will generate `.in(jsonBody[String])` (or `.out(jsonBody[String])`) when `@command`'s input (or output) is a plain String.

Controller implementations are forced to provide JsonCodec's for types that should be supported out-of-the-box.

/cc @calippo

**Comment by tpetrucciani** [comment]
For what concerns `String` output, now we behave differently from wiro and I'm not sure we want to.

Now in tapiro when the output type is `String` we use `stringBody`: this means that we respond with `Content-Type: text/plain; charset=UTF-8` and the body is the raw string.

Instead, wiro always responds with `Content-Type: application/json` and the body is always a JSON value: in particular, if it's a string, it's a JSON string (i.e. it has quotes around it).

I'm more in favour of the wiro approach (it's simpler and it doesn't require changes in the frontend code), but I don't know if you already discussed this difference.

@calippo @giuscri what do you think about this?

For the inputs, instead, maybe we don't need to handle this here because if we do #203 then POST inputs will always be wrapped in an object.

**Comment by calippo** [comment]
This was not already discussed @tpetrucciani I agree with what you said

**Comment by giuscri** [comment]
@tpetrucciani, I too think having strings encoded like any other json is simpler. I probably made the wrong considerations. The commit to revert is 0a856a8df6251fb0c9c98648f2f44b4a6db355a7

**Comment by giuscri** [comment]
Fixed by https://github.com/buildo/retro/pull/212
